[project]
name = "pytonb"
version = "0.1.1"
description = "simple converter py<->notebook with sync function"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.10"
license = { file = "LICENSE" }   


dependencies = [
    "bandit>=1.8.6",
]

# dev
[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "import-ipynb>=0.2",
    "notebook>=7.4.7",
    "ruff>=0.14.0",
    "pytest-cov>=7.0.0",
    "black>=25.9.0",
    "sphinx>=8.1.3",
    "sphinx-autodoc-typehints>=3.0.1",
]

# test
[tool.pytest.ini_options]
testpaths = ['test']


# build
[build-system]
#requires = ["setuptools"]
#build-backend = "setuptools.build_meta"
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"


# linting
[tool.ruff]
target-version = "py313"
line-length = 110

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]   # enable
ignore = ["E731" ]        # ignore 

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "D"]       

