name: Publish to PyPI

on:
  push:
    tags:
      - "v*"          # publish when we push a tag like v0.1.0
  workflow_dispatch:

permissions:
  id-token: write     # required for OIDC
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install uv and put it on PATH
      - uses: astral-sh/setup-uv@v6
      - run: uv --version

      # Install project + dev deps (ensure pytest is in your dev group)
      - name: Sync deps
        run: uv sync --dev

      # Run tests (customize as needed)
      - name: Pytest
        run: uv run pytest -q

      # Build distribution if tests passed
      - name: Build
        run: uv build

      # Share the build with the next job
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  publish:
    environment: pypi 
    permissions:
      id-token: write  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6   # puts `uv` on PATH
      - run: uv --version

      - name: Build
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
